language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
install:
  - composer install
services:
  - mysql
env:
  - MYSQL_HOST=localhost MYSQL_USER=root
script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml
after_script:
 - vendor/bin/coveralls -v
