language: php
php:
  - 7.1
install:
  - composer install
services:
  - mysql
  - postgresql
env:
  - MYSQL_HOST=localhost MYSQL_USER=root PGSQL_HOST=localhost PGSQL_USER=postgres
script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
 - vendor/bin/coveralls -v
